Created custom plugin to display topics sorted by bookmark count
CMU-313/spring23-nodebb-team-up pull request #21
Opened 2023-03-01 16:46 UTC by amitag2

2023-03-01 16:51 UTC, Quarks-1 requested changes
A couple of things are missing here.  It would be helpful to add edge cases, one such being a case where no topics are present, to the testing suite.  Also, some files don't pass the linter and could use some fixed indentation (minor fix).  Other than those things looks great!

2023-03-02 01:45 UTC, amitag2 commented
> A couple of things are missing here. It would be helpful to add edge cases, one such being a case where no topics are present, to the testing suite. Also, some files don't pass the linter and could use some fixed indentation (minor fix). Other than those things looks great!

Good catch! Just made those changes

2023-03-02 03:47 UTC, Quarks-1 approved these changes

2023-03-02 03:48 UTC, Quarks-1 approved these changes
Everything looks good!

2023-03-02 03:48 UTC, merged